"""
build_cohort_manifest.py - generate config/cohort.json from the share ground truth.

The cohort statistics script (06_cohort_stats.py) joins per-subject results against a manifest of
{id, group, age}. That manifest used to be hand-maintained, which drifts whenever a subject is added
or a scan date changes. This regenerates it deterministically from the share so there is one source of
truth: the canonical subject set is the MUDI_synb0 folder list, and age/sex come from
Subjects/SubjectsInfo.txt. group is inferred from the subject id (Patient -> PD, Control -> HC), the
only naming convention in this cohort.

The ids embed scan dates, so config/cohort.json is gitignored; this generator is the tracked,
shareable way to recreate it on any machine with the share mounted.

Usage:
  simnibs_python analysis/build_cohort_manifest.py [--share DIR] [--out FILE] [--montages M1 DLPFC ...]
  COHORT_SHARE is the default --share. --montages must list only montages actually run by the cohort
  runner (06 needs a roi_efield_<montage>.csv per listed montage); default M1.
"""
import os, sys, json, argparse

GROUP_FROM_ID = [("patient", "PD"), ("control", "HC")]   # substring (case-insensitive) -> group


def infer_group(subject_id):
    low = subject_id.lower()
    hits = [g for token, g in GROUP_FROM_ID if token in low]
    if len(hits) != 1:
        raise ValueError(f"cannot infer group for {subject_id!r}: matched {hits or 'nothing'} "
                         f"(expected exactly one of Patient/Control in the id)")
    return hits[0]


def read_subjects_info(path):
    """Parse 'id<ws>age<ws>sex' lines into {id: (age:int, sex:str)}. Blank/short lines are skipped."""
    info = {}
    with open(path) as f:
        for ln in f:
            parts = ln.split()
            if len(parts) < 3:
                continue
            sid, age, sex = parts[0], parts[1], parts[2]
            try:
                age_val = int(round(float(age)))   # accept "62" or "62.5"; round to whole years
            except ValueError:
                print(f"  warning: row for {sid} has a non-numeric age {age!r}; skipping that row")
                continue
            info[sid] = (age_val, sex)
    return info


def list_subjects(share):
    """Canonical subject set = MUDI_synb0 subdirectories (dotfiles excluded)."""
    mudi = os.path.join(share, "MUDI_synb0")
    if not os.path.isdir(mudi):
        raise FileNotFoundError(f"{mudi} not found (mount the cohort share or pass --share)")
    return sorted(d for d in os.listdir(mudi)
                  if not d.startswith(".") and os.path.isdir(os.path.join(mudi, d)))


def build(share, montages):
    info = read_subjects_info(os.path.join(share, "Subjects", "SubjectsInfo.txt"))
    subjects, missing = [], []
    for sid in list_subjects(share):
        if sid not in info:
            missing.append(sid); continue
        age, sex = info[sid]
        subjects.append({"id": sid, "group": infer_group(sid), "age": age, "sex": sex})
    if missing:
        raise ValueError(f"{len(missing)} subject(s) in MUDI_synb0 absent from SubjectsInfo.txt: "
                         f"{', '.join(missing)}")
    return {
        "_comment": ("Generated by analysis/build_cohort_manifest.py from the share "
                     "Subjects/SubjectsInfo.txt + MUDI_synb0. ids match results/<id>/. "
                     "group: PD=Patient, HC=Control. montages must list only montages actually run. "
                     "Gitignored: ids embed scan dates."),
        "montages": list(montages),
        "subjects": subjects,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--share", default=os.environ.get("COHORT_SHARE", ""))
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config", "cohort.json"))
    ap.add_argument("--montages", nargs="+", default=["M1"])
    args = ap.parse_args()
    if not args.share:
        sys.exit("set COHORT_SHARE or pass --share <cohort_data dir>")

    manifest = build(args.share, args.montages)
    subs = manifest["subjects"]
    n_pd = sum(s["group"] == "PD" for s in subs)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(f"wrote {args.out}: {len(subs)} subjects ({n_pd} PD, {len(subs) - n_pd} HC); "
          f"montages={manifest['montages']}")


if __name__ == "__main__":
    main()
